### ISSUE TITLE
enshrined/svg-sanitize dependency error with CraftCMS 3

### ISSUE THREAD

**Issue by mixplatemedia** [enovatedesign/craft-style-inliner#15]
I can't update Craft CMS from 3.8.3 to 3.8.4 using composer.

Can you update the required version of enshrined/svg-sanitize in the latest version of enovatedesign/craft-style-inliner please? 

Thank you!

**Comment by Enovate-Jordan** [comment]
Hi @mixplatemedia, both versions `3.8.3` and `3.8.4` of Craft Cms use `enshrined/svg-sanitize` `~0.15.2`. I suggest that until you're using a later version of Craft Cms you lock the version of this plugin to `2.4.0`, which is the latest Craft 3 compatible version of this plugin.

Let me know if that resolves your issue

**Comment by mixplatemedia** [comment]
Whoops, my mistake. You're right, but it looks like the latest version is CraftCMS 3.8.5 which was shipped the day after 3.8.4. We were trying to upgrade to 3.8.5 which uses ~0.16.0 svg-sanitizer.  Let me know.

**Comment by Enovate-Jordan** [comment]
Hi @mixplatemedia, I added a new release `2.5.0`. Update this plugin to `2.5.0`, let me know if that resolves your issue.

**Comment by mixplatemedia** [comment]
Yup, that did it. Thank you!
