### ISSUE TITLE
Error on sending emails

### ISSUE THREAD

**Issue by primariu-dev-team** [enovatedesign/craft-style-inliner#16]
Hi, when i try to send the forgot password i get an error like this.
<img width="453" alt="Captura de ecrã 2023-03-29, às 18 13 17" src="https://user-images.githubusercontent.com/122789902/228616397-3b81c253-60f8-4c6d-9a46-29a3806ed39d.png">

I went to check and this is a problem on your extension where Your php file CriticalCssNode is using the old class \Twig_Compiler instead of the new class \Twig\Compiler

**Comment by Enovate-Jordan** [comment]
Hi @primariu-dev-team, I have released a fix for this. Update this plugin to 3.0.4 and let me know if that resolves your issue.

**Comment by primariu-dev-team** [comment]
Hi it fixed, thank you.
