### ISSUE TITLE
Has v3.0.4 been officially released?

### ISSUE THREAD

**Issue by jonleverrier** [enovatedesign/craft-style-inliner#18]
The reason I ask, is that I cannot find [v3.0.4](https://github.com/enovatedesign/craft-style-inliner/issues/17#issuecomment-1573253284) on Packagist or on the Craft Plugin store, so can't update from v3.0.3

**Comment by Enovate-Jordan** [comment]
I have updated the version number in composer.json. You should be able to update to the latest version of this package now, which is `3.0.5`.
