### ISSUE TITLE
Craft 5 support

### ISSUE THREAD

**Issue by jonleverrier** [enovatedesign/craft-style-inliner#21]
Are there any plans to upgrade Style Inliner to Craft 5?

**Comment by mtwalsh** [comment]
Yes, we do already have a [pull request](https://github.com/enovatedesign/craft-style-inliner/pull/20) for this, it seems to be working fine thus far so should be merged in shortly.

**Comment by jonleverrier** [comment]
Strange - not being picked up / tagged as Craft 5 ready on the plugin store @mtwalsh 
https://plugins.craftcms.com/style-inliner

<img width="453" alt="Screenshot 2024-04-17 at 14 13 16" src="https://github.com/enovatedesign/craft-style-inliner/assets/2373940/f0ceddef-1cdc-4809-9dff-e5fdb74dae7e">

**Comment by jonleverrier** [comment]
Is that line correct @mtwalsh ?
https://github.com/enovatedesign/craft-style-inliner/blob/73762ba7f50962236fb9cd6880e0ff1740f2c9bb/composer.json#L11

Craft 5 is only at v5.0.4 at the time of writing.

**Comment by mtwalsh** [comment]
Nope, well spotted, @Enovate-Jordan is on the case!
