### ISSUE TITLE
Craft 4.11.x support

### ISSUE THREAD

**Issue by engram-design** [enovatedesign/craft-style-inliner#23]
Looks like [Craft 4.11.x](https://github.com/craftcms/cms/releases/tag/4.11.0) has updated the constraint for `enshrined/svg-sanitize` from `0.16.0` to `0.19.0`, and this plugin won't work on that.

I was putting together a PR, but I wasn't sure how you'd like to version things. I see your version constraint for Craft is just `^4.0`, and I would think you'd release a `3.1.0` of this plugin and change the Craft version constraint to `^4.11.0` as well.

Related to https://github.com/verbb/formie/issues/2009

**Comment by Enovate-Jordan** [comment]
Hi @engram-design,

That sounds exactly right to me. If you don't mind, feel free to make a PR and I'll review it. If not I'll get around to it later today.

**Comment by engram-design** [comment]
Happy to do a PR, I just can't target a branch as there's nothing in this repo with the `3.x` code. https://github.com/enovatedesign/craft-style-inliner/pull/24

**Comment by Enovate-Jordan** [comment]
Thank you @engram-design, that's been merged in and released
